### ISSUE TITLE
closing itself rly quick after i type eu and hit enter

### ISSUE THREAD

**Issue by icc1412** [deadly/valorant-agent-yoinker#12]
i could take a screenshot before it closed itself. its this one https://gyazo.com/390054e0e0a929c7c88e7fed804debe1

**Comment by deadly** [comment]
read your own screenshot and you'll figure out the issue.

**Comment by icc1412** [comment]
idk what you mean by that ^^' my val was running if you mean that. idk what everything else on there means. sry im not a programmer.

**Comment by deadly** [comment]
if your valorant is open, try running the .exe as administrator. let me know if that works

**Comment by icc1412** [comment]
i did it, it just closes itself in a split second :c

**Comment by icc1412** [comment]
it works again. idk how tho. i didnt make any changes
