### ISSUE TITLE
Kills my in-game ping?

### ISSUE THREAD

**Issue by ghost** [deadly/valorant-agent-yoinker#13]
As soon as I play a match with it my ping is suddenly always over 200. I'm pretty sure this is the cause of my issue, but I'm not sure as it doesn't go away even after closing the tool.

**Comment by deadly** [comment]
if this is for sure the cause of your issue, try changing the loopDelay to a higher number.

**Comment by ghost** [comment]
Seems to have worked, thanks for great tool.
