### ISSUE TITLE
Got Banned by Using Agent Yoinker 2.0

### ISSUE THREAD

**Issue by FluffySteini** [deadly/valorant-agent-yoinker#22]
My Account was locked after the first time  i used it... 
![AgentYoinker2 0 issue](https://github.com/deadly/valorant-agent-yoinker/assets/113844767/9877822a-ca63-4a69-a707-b5ad89fbcf89)

**Comment by deadly** [comment]
Please see the readme.

**Comment by FluffySteini** [comment]
in the README IS NOTHING THAT SAYS SOMETHING ABOUNT BANS...

**Comment by deadly** [comment]
Yes, it did. It mentioned the potential API abuse suspensions that could occur. It also said, "USE AT YOUR OWN RISK."

It has also now been updated to state that suspensions are now occurring and are no longer potential.
